version: '2'
services:
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - schedule
    links:
      - schedule:schedule
    depends_on:
      - schedule
  schedule:
    restart: always
    build: ./scheduler/
    expose:
      - "8000"
    volumes:
      - /usr/src/app
      - /usr/src/app/static